### ISSUE TITLE
Miscellaneous thoughts

### ISSUE THREAD

**Issue by Pyromanc3r** [CrossVas/BlockHelperAddons#1]
Just some thoughts. The Geothermal Generator is showing excessive information. I am using the "BlockHelper-1.2.0-pre2-1.5.x". 
The lines "Lava" and "Fuel" have the same info. It would be nice to leave something alone.
![2024-04-25_13 11 41](https://github.com/CrossVas/BlockHelperAddonsIC2/assets/17619385/f8c392fd-7a6f-4b5d-9e7b-68f99e24cc12)

Also, I was thinking that since you're adding extended info for IC2, it might be worth it for GregTech 3 as well?
![2024-04-25_13 14 02](https://github.com/CrossVas/BlockHelperAddonsIC2/assets/17619385/23499aff-fa7c-4f0a-9ad4-b99e499658a9)

I want to make a little modpack for myself (1.5.2) and play GT3, since I missed that version and I'm curious what that mod was capable of back in the day. Plus I found your new addons and it came in handy (gravisuite, vintagehopperdiet).
It would also be nice to have support for the Mine Factory Reloaded. But it's not a necessity. It seems that no plugins have been created for this mod at all, not even for NEI. Or I don't know about it.

Do you know any other interesting mods that will go well with GT3 (besides the classic Forestry and BuildCraft)? But I would like to focus on Gregtech.

I wanted to install the Modular Powersuits mod, but the original author's site is no longer exist, and there are no 1.5.2 releases left on his Github and Curseforge
https://web.archive.org/web/20181128224220/http://www.machinemuse.net/download.php
https://github.com/MachineMuse/MachineMusePowersuits/tree/1.5.2 
I can't find this mod =\

**Comment by CrossVas** [comment]
[mods.zip](https://github.com/CrossVas/BlockHelperAddonsIC2/files/15110836/mods.zip)
Here is the zip with Moular Powersuit, Modular Powersuit Addons. Also, there is a small addition for GregTech3, which adds some missing ingots dusts from from GT4 [here](https://github.com/CrossVas/GregTechCompanion-1.5.2)

Now to get to your questions.

1. The `Fuel` thing will stay until I figure a way to add better support for FluidHandlers and EnergyHandlers. This might be done by overriding the current builtin forge compat addon. This will take a while.

2. I have this planed, but this will also require me some time to finish, as I'm currently in the process making a list of wanted information. 

3. MFR Support? This would be nice to have done after I figure out the 1 point. Not sure yet.
