### ISSUE TITLE
Server side issue

### ISSUE THREAD

**Issue by Pyromanc3r** [CrossVas/BlockHelperAddons#3]
Hello again. It looks like the mod doesn't work on the server side. And without it, the game client does not receive extended information.
By the way, there was a similar error with Gravisuite. The mod crashes on a dedicated server :(

https://mclo.gs/qs23woD

**Comment by CrossVas** [comment]
[BlockHelperAddons-1.5.2-1.0.2.2.jar.zip](https://github.com/user-attachments/files/16119440/BlockHelperAddons-1.5.2-1.0.2.2.jar.zip)
Could you try this one and see if the issue is still there?
As for gravisuite problem, please provide the crashlog.

**Comment by CrossVas** [comment]
https://github.com/CrossVas/BlockHelperAddons/releases/tag/1.0.2.2

**Comment by Pyromanc3r** [comment]
Now I can log into the server, but something is clearly broken here...


![2024-07-07_17 24 13](https://github.com/CrossVas/BlockHelperAddons/assets/17619385/84a6c67d-a2ac-4e95-afaa-946a9b6c2d5d)
![2024-07-07_17 25 25](https://github.com/CrossVas/BlockHelperAddons/assets/17619385/576f1d5d-99fa-464c-8955-77ca16916b85)

**Comment by CrossVas** [comment]
[BlockHelperAddons-1.5.2-1.0.2.2pre.jar.zip](https://github.com/user-attachments/files/16120005/BlockHelperAddons-1.5.2-1.0.2.2pre.jar.zip)

**Comment by CrossVas** [comment]
The thing is. I don't play on server, so I have no real setup to test things out. Sorry.

**Comment by Pyromanc3r** [comment]
I understand. I just decided to invite a friend to play together and when testing I encountered this unexpected problem
Version 1.0.2.2pre also crashes https://mclo.gs/bxy6g1n

Here is my mini test-server, if this helps you in any way (edit the Start.bat file for your version of Java)
https://www.mediafire.com/file/wlcd5xkfs1b4nc2/1.5.2-test-server.7z/file

**Comment by CrossVas** [comment]
[BlockHelperAddons-1.5.2-1.0.2.2pre.jar.zip](https://github.com/user-attachments/files/16120355/BlockHelperAddons-1.5.2-1.0.2.2pre.jar.zip)
Try this one

**Comment by Pyromanc3r** [comment]
Seems to work :) Thanks!
I quickly checked all the blocks from IC2 and GT. There were a couple of strange descriptions. 
![2024-07-07_22 04 12](https://github.com/CrossVas/BlockHelperAddons/assets/17619385/bbdd4485-ef50-4882-8b8a-dc1790d0e854)
(all types Transformers same)

![2024-07-07_22 08 21](https://github.com/CrossVas/BlockHelperAddons/assets/17619385/ef207601-23d4-4d15-82cb-63def97b0469)
![2024-07-07_22 13 14](https://github.com/CrossVas/BlockHelperAddons/assets/17619385/7b56ceac-adae-49da-bb6d-c14592ac87d6)
![2024-07-07_22 16 18](https://github.com/CrossVas/BlockHelperAddons/assets/17619385/f0af7a28-a126-4b1e-b1b8-fcc9eb04dbbd)

That's all.
And is also no information on Quantum Tank (maybe it wasn’t there, I didn’t notice)

**Comment by CrossVas** [comment]
I'll test it tomorrow. And release a full version. Keep an eye on release tab.

**Comment by Pyromanc3r** [comment]
Thank you again!

**Comment by CrossVas** [comment]
Okay, most of this was easy fix.
There is 1 problem tho. `Wrenchable Info` cannot be loaded due to how `BlockHelper` handle things. This means, there will be no info about Wrench Drop Chance, and I can't fix it without having to go extra.

**Comment by Pyromanc3r** [comment]
Singleplayer. This is only visible on IC2 blocks. GT is fine.
![2024-07-08_14 17 02](https://github.com/CrossVas/BlockHelperAddons/assets/17619385/d980b801-64bd-4107-9322-49fd1a46eceb)
Also Quantum Chest now does not show the number of items inside (earlier in the screenshot above it just showed 128 items as 12800%).

**Comment by CrossVas** [comment]
> Also Quantum Chest now does not show the number of items inside (earlier in the screenshot above it just showed 128 items as 12800%).

Yes, this was deprecated until I find a better way to show progress/internal storage for blocks. 
Clearly there was no progress and formatting were broken.
